#!/usr/bin/env bash
# Send a file to a remote server
# $1 = The file to be sent
# $2 = The ip address of the remover server
# $3 = The username of the remote server
# $4 = The path on the remote server to store the file

if [ "$#" -lt 3 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
