#!/usr/bin/env bash
# Install and setup Nginx web server
sudo apt-get update -qq
sudo apt-get install nginx -y

# Start the server if not already running
sudo service nginx start

# Allow HTTP traffic i.e listen on port 80
sudo ufw allow 'Nginx HTTP'

# Change the ownership of the website to current user and group.
sudo chown -R "$USER":"$USER" /var/www/html

# Make all users be able to read and execute the website files, but only owner can write
sudo chmod -R 755 /var/www

# Set the default request to return "Hello World!"
echo "Hello World!" | dd status=none of=/var/www/html/index.html

# Setting up /redirect_me to a youtube video
sudo sed -i '24i\	rewrite ^/redirect_me https://goal.com permanent;' /etc/nginx/sites-available/default

# Set up a 404 page
echo "Ceci n'est pas une page" >> /var/www/html/error_404.html
sudo sed -i '25i\	error_page 404 /error_404.html;' /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart
