#!/usr/bin/env bash
# Display numbers from 1 to 20. Display 4 and then bad luck
#+ from China for the 4th loop iteration, display 9 and then
#+ bad luck from Japan for the 9th loop iteration and display
#+ 17 and then bad luck from Italy for the 17th loop iteration

x=1

while [ $x -le 20 ]
do
	echo "$x"
	if [ $x -eq 4 ]
	then
		echo "bad luck from China"
	elif [ $x -eq 9 ]
	then
		echo "bad luck from Japan"
	elif [ $x -eq 17 ]
	then
		echo "bad luck from Italy"
	fi
	(( x++ ))
done
