#!/usr/bin/env bash
# Display regular files in the current directory

FILE=$(ls)

for file in $FILE;
do
	if [ -f "$file" ] && [[ "$file" != .* ]];
	then
		name=$(echo "$file" | cut -d'-' -f2-)
		echo "$name"
	fi
done
